---
- name: Include vars for r1
  include_vars: r1.yml
  when: ansible_hostname == 'r1'

- name: Include vars for r2
  include_vars: r2.yml
  when: ansible_hostname == 'r2'

- name: Include vars for r3
  include_vars: r3.yml
  when: ansible_hostname == 'r3'

- name: Set sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    ignoreerrors: true
    reload: true
  with_dict: "{{ sysctl_params }}"


- name: Set zebra conf
  template:
    src: templates/zebra.conf.j2
    dest: /etc/quagga/zebra.conf
    owner: root
    group: root
    mode: 0644
  notify: restart zebra

- name: Set ospfd conf
  template:
    src: templates/ospfd.conf.j2
    dest: /etc/quagga/ospfd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ospfd