---
- hosts: r1
  name: Setup r1
  become: yes
  roles:
    - role: r1

- hosts: r2
  name: Setup r2
  become: yes
  roles:
    - role: r2

- hosts: r3
  name: Setup r3
  become: yes
  roles:
    - role: r3