---
- hosts: all
  name: Setup soft
  become: true
  pre_tasks: 
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install quagga
    yum:
      name: quagga
      state: present

- hosts: all
  name: Setup routers
  become: true
  roles:
    - role: router-install
